### ISSUE TITLE
build fails with master

### ISSUE THREAD

**Issue by KlavsKlavsen** [ImmobilienScout24/yum-repo-server#69]
mvn package - ends with this:

[DEBUG] Source roots:
[DEBUG]  /home/b56v/yum-repo-server/src/main/java
[DEBUG] Command line options:
[DEBUG] -d /home/b56v/yum-repo-server/target/classes -classpath /home/b56v/yum-repo-server/target/classes:/home/b56v/.m2/repository/org/mongodb/mongo-java-driver/3.2.1/mongo-java-driver-3.2.1.jar:/home/b56v/.m2/repository/org/springframework/spring-tx/4.2.4.RELEASE/spring-tx-4.2.4.RELEASE.jar:/home/b56v/.m2/repository/org/springframework/spring-beans/4.2.4.RELEASE/spring-beans-4.2.4.RELEASE.jar:/home/b56v/.m2/repository/org/springframework/spring-core/4.2.4.RELEASE/spring-core-4.2.4.RELEASE.jar:/home/b56v/.m2/repository/org/springframework/data/spring-data-mongodb/1.8.2.RELEASE/spring-data-mongodb-1.8.2.RELEASE.jar:/home/b56v/.m2/repository/org/springframework/data/spring-data-commons/1.11.2.RELEASE/spring-data-commons-1.11.2.RELEASE.jar:/home/b56v/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.13/jcl-over-slf4j-1.7.13.jar:/home/b56v/.m2/repository/org/apache/tomcat/tomcat-servlet-api/7.0.39/tomcat-servlet-api-7.0.39.jar:/home/b56v/.m2/repository/org/slf4j/slf4j-log4j12/1.7.5/slf4j-log4j12-1.7.5.jar:/home/b56v/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar:/home/b56v/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/home/b56v/.m2/repository/org/springframework/spring-webmvc/4.2.4.RELEASE/spring-webmvc-4.2.4.RELEASE.jar:/home/b56v/.m2/repository/org/springframework/spring-context/4.2.4.RELEASE/spring-context-4.2.4.RELEASE.jar:/home/b56v/.m2/repository/org/springframework/spring-expression/4.2.4.RELEASE/spring-expression-4.2.4.RELEASE.jar:/home/b56v/.m2/repository/org/springframework/spring-web/4.2.4.RELEASE/spring-web-4.2.4.RELEASE.jar:/home/b56v/.m2/repository/org/springframework/spring-aop/4.2.4.RELEASE/spring-aop-4.2.4.RELEASE.jar:/home/b56v/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/home/b56v/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:/home/b56v/.m2/repository/com/google/guava/guava/17.0/guava-17.0.jar:/home/b56v/.m2/repository/org/kohsuke/libpam4j/1.8/libpam4j-1.8.jar:/home/b56v/.m2/repository/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar:/home/b56v/.m2/repository/de/is24/common/appmon4j-core/1.58/appmon4j-core-1.58.jar:/home/b56v/.m2/repository/de/is24/common/appmon4j-spring/1.58/appmon4j-spring-1.58.jar:/home/b56v/.m2/repository/org/springframework/security/spring-security-web/4.0.3.RELEASE/spring-security-web-4.0.3.RELEASE.jar:/home/b56v/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/home/b56v/.m2/repository/org/springframework/security/spring-security-core/4.0.3.RELEASE/spring-security-core-4.0.3.RELEASE.jar:/home/b56v/.m2/repository/org/springframework/security/spring-security-config/4.0.3.RELEASE/spring-security-config-4.0.3.RELEASE.jar:/home/b56v/.m2/repository/org/redline-rpm/redline/1.1.16/redline-1.1.16.jar:/home/b56v/.m2/repository/org/apache/ant/ant/1.9.1/ant-1.9.1.jar:/home/b56v/.m2/repository/org/apache/ant/ant-launcher/1.9.1/ant-launcher-1.9.1.jar:/home/b56v/.m2/repository/org/tukaani/xz/1.4/xz-1.4.jar:/home/b56v/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/home/b56v/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.6.4/jackson-databind-2.6.4.jar:/home/b56v/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.6.0/jackson-annotations-2.6.0.jar:/home/b56v/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.6.4/jackson-core-2.6.4.jar:/home/b56v/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar:/home/b56v/.m2/repository/org/glassfish/web/jstl-impl/1.2/jstl-impl-1.2.jar:/home/b56v/.m2/repository/org/aspectj/aspectjrt/1.8.2/aspectjrt-1.8.2.jar:/home/b56v/.m2/repository/org/aspectj/aspectjweaver/1.8.2/aspectjweaver-1.8.2.jar:/home/b56v/.m2/repository/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:/home/b56v/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar:/home/b56v/.m2/repository/org/xerial/sqlite-jdbc/3.7.2/sqlite-jdbc-3.7.2.jar:/home/b56v/.m2/repository/org/tuckey/urlrewritefilter/4.0.4/urlrewritefilter-4.0.4.jar:/home/b56v/.m2/repository/joda-time/joda-time/2.4/joda-time-2.4.jar:/home/b56v/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar:/home/b56v/.m2/repository/org/bouncycastle/bcpg-jdk15on/1.51/bcpg-jdk15on-1.51.jar:/home/b56v/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.51/bcprov-jdk15on-1.51.jar:/home/b56v/.m2/repository/org/slf4j/jul-to-slf4j/1.7.6/jul-to-slf4j-1.7.6.jar:/home/b56v/.m2/repository/org/springframework/boot/spring-boot-starter-web/1.1.5.RELEASE/spring-boot-starter-web-1.1.5.RELEASE.jar:/home/b56v/.m2/repository/org/springframework/boot/spring-boot-starter/1.1.5.RELEASE/spring-boot-starter-1.1.5.RELEASE.jar:/home/b56v/.m2/repository/org/springframework/boot/spring-boot/1.1.5.RELEASE/spring-boot-1.1.5.RELEASE.jar:/home/b56v/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/1.1.5.RELEASE/spring-boot-autoconfigure-1.1.5.RELEASE.jar:/home/b56v/.m2/repository/org/springframework/boot/spring-boot-starter-logging/1.1.5.RELEASE/spring-boot-starter-logging-1.1.5.RELEASE.jar:/home/b56v/.m2/repository/org/hibernate/hibernate-validator/5.0.3.Final/hibernate-validator-5.0.3.Final.jar:/home/b56v/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar:/home/b56v/.m2/repository/org/jboss/logging/jboss-logging/3.1.1.GA/jboss-logging-3.1.1.GA.jar:/home/b56v/.m2/repository/com/fasterxml/classmate/1.0.0/classmate-1.0.0.jar: -sourcepath /home/b56v/yum-repo-server/src/main/java: -s /home/b56v/yum-repo-server/target/generated-sources/annotations -g -nowarn -target 1.8 -source 1.8 -encoding UTF-8
[DEBUG] incrementalBuildHelper#beforeRebuildExecution
[INFO] Compiling 146 source files to /home/b56v/yum-repo-server/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.335s
[INFO] Finished at: Thu Jun 02 12:40:34 CEST 2016
[INFO] Final Memory: 10M/28M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project yum-repo-server: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project yum-repo-server: Fatal error compiling
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
Caused by: org.apache.maven.plugin.MojoExecutionException: Fatal error compiling
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:796)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: org.codehaus.plexus.compiler.CompilerException: invalid target release: 1.8
        at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:191)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:169)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:785)
        ... 22 more
Caused by: java.lang.IllegalArgumentException: invalid target release: 1.8
        at com.sun.tools.javac.main.RecognizedOptions$GrumpyHelper.error(RecognizedOptions.java:88)
        at com.sun.tools.javac.main.RecognizedOptions$10.process(RecognizedOptions.java:359)
        at com.sun.tools.javac.api.JavacTool.processOptions(JavacTool.java:242)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:199)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:68)
        at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:115)
        ... 24 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by KlavsKlavsen** [comment]
arghh. missing javac linking to 1.8.0 version..
